import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import "./globals.css";


export const metadata = {
  title: "Server Stats Bot",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-[#1c2330]">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
